[2024-05-26T08:32:21.011+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: locations_init_dag.connect_to_db manual__2024-05-26T08:32:19.516005+00:00 [queued]>
[2024-05-26T08:32:21.017+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: locations_init_dag.connect_to_db manual__2024-05-26T08:32:19.516005+00:00 [queued]>
[2024-05-26T08:32:21.017+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-26T08:32:21.025+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): connect_to_db> on 2024-05-26 08:32:19.516005+00:00
[2024-05-26T08:32:21.034+0000] {standard_task_runner.py:60} INFO - Started process 300 to run task
[2024-05-26T08:32:21.036+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'locations_init_dag', 'connect_to_db', 'manual__2024-05-26T08:32:19.516005+00:00', '--job-id', '2284', '--raw', '--subdir', 'DAGS_FOLDER/locations_init_dag.py', '--cfg-path', '/tmp/tmpki46q8r8']
[2024-05-26T08:32:21.038+0000] {standard_task_runner.py:88} INFO - Job 2284: Subtask connect_to_db
[2024-05-26T08:32:21.048+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-26T08:32:21.068+0000] {task_command.py:423} INFO - Running <TaskInstance: locations_init_dag.connect_to_db manual__2024-05-26T08:32:19.516005+00:00 [running]> on host d904a9488f34
[2024-05-26T08:32:21.104+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='locations_init_dag' AIRFLOW_CTX_TASK_ID='connect_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T08:32:19.516005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-26T08:32:19.516005+00:00'
[2024-05-26T08:32:21.109+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-26T08:32:21.114+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=locations_init_dag, task_id=connect_to_db, execution_date=20240526T083219, start_date=20240526T083221, end_date=20240526T083221
[2024-05-26T08:32:21.128+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-26T08:32:21.143+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
