[2024-05-26T08:32:25.024+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: locations_init_dag.populate_locations_task manual__2024-05-26T08:32:19.516005+00:00 [queued]>
[2024-05-26T08:32:25.027+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: locations_init_dag.populate_locations_task manual__2024-05-26T08:32:19.516005+00:00 [queued]>
[2024-05-26T08:32:25.027+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-26T08:32:25.032+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): populate_locations_task> on 2024-05-26 08:32:19.516005+00:00
[2024-05-26T08:32:25.037+0000] {standard_task_runner.py:60} INFO - Started process 312 to run task
[2024-05-26T08:32:25.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'locations_init_dag', 'populate_locations_task', 'manual__2024-05-26T08:32:19.516005+00:00', '--job-id', '2288', '--raw', '--subdir', 'DAGS_FOLDER/locations_init_dag.py', '--cfg-path', '/tmp/tmp16t86k7v']
[2024-05-26T08:32:25.040+0000] {standard_task_runner.py:88} INFO - Job 2288: Subtask populate_locations_task
[2024-05-26T08:32:25.048+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-26T08:32:25.063+0000] {task_command.py:423} INFO - Running <TaskInstance: locations_init_dag.populate_locations_task manual__2024-05-26T08:32:19.516005+00:00 [running]> on host d904a9488f34
[2024-05-26T08:32:25.093+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='locations_init_dag' AIRFLOW_CTX_TASK_ID='populate_locations_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T08:32:19.516005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-26T08:32:19.516005+00:00'
[2024-05-26T08:32:25.105+0000] {locations_init_dag.py:97} INFO - Populating locations...
[2024-05-26T08:32:25.659+0000] {locations_init_dag.py:111} INFO - Locations populated successfully.
[2024-05-26T08:32:25.659+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-26T08:32:25.664+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=locations_init_dag, task_id=populate_locations_task, execution_date=20240526T083219, start_date=20240526T083225, end_date=20240526T083225
[2024-05-26T08:32:25.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-26T08:32:25.705+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
